name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy service
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: "1.25.0"
      - run: make sqlc-generate
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
